inventory/config/routes.rb
# frozen_string_literal: true

Inventory::Engine.routes.draw do
resources :edits_inv do
  collection {post :import}
end

resources :edits_auin do
  collection {post :import}
end


get 'views' => 'views#index', as: 'views'
get 'get_inv_views' => 'views#get_inv_views', as: 'get_inv_views'



end

inventory/app/models/inventory/application_record.rb
# frozen_string_literal: true

module Inventory
  # Inventory application records
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

inventory/app/controllers/inventory/application_controller.rb
# frozen_string_literal: true

module Inventory
  # Inventory controller
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

inventory/app/controllers/inventory/edits_auin_controller.rb
# frozen_string_literal: true

module Inventory
  # AUIN edit controller
  class EditsAuinController < ApplicationController

    def index
      @auin_attributes = AwmsAuinAttribute.all
      @missing_attr = AwmsAuinAttribute.missing_attr_location

    end

    def import
      AwmsAuinAttribute.csv_update(params[:file])
      redirect_to({ :action => :index },
                  { :success => 'AUIN attributes updated!' })
    end

    def edit_auin

    end

  end
end

inventory/app/controllers/inventory/edits_inv_controller.rb
# frozen_string_literal: true

module Inventory
  # Inventory Edits controller
  class EditsInvController < ApplicationController

    def index
      @inv_items = AwmsInvItem.all
    end

    def import
      case AwmsInvItem.csv_update(params[:file])
      when 'SUCCESS'
        redirect_to({ :action => :index },
                    { :success => 'Inventory updated!' })
      when  'FAILURE'
        redirect_to({ :action => :index },
                    { :error => 'Location ID not a valid location!' })
      end
    end

    def edit_inv

    end

  end
end

inventory/app/controllers/inventory/views_controller.rb
# frozen_string_literal: true

module Inventory
  # Class for inventory viewing
  class ViewsController < ApplicationController
    def index

    end

    def get_inv_views
      @inv_views_attributes = AwmsAuinAttribute.where(auin: params[:auin])
      if !@inv_views_attributes.blank?
        @inv_views_attributes = @inv_views_attributes.first
      end
      puts @inv_views_attributes.inspect
      @inv_views_locations = AwmsInvItem.where(auin: params[:auin])
    end

  end
end

inventory/app/helpers/inventory/application_helper.rb
# frozen_string_literal: true

module Inventory
  # Inventory helpers
  module ApplicationHelper
  end
end

inventory/app/views/inventory/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "inventory/application", media: "all" %>
  <%= javascript_include_tag "inventory/application" %>
</head>
<body>

<%= yield %>

</body>
</html>

inventory/app/views/inventory/edits_auin/index.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>
</div>
<table class="table table-condensed table-bordered table-striped">
  <thead>
    <tr>
      <th> AUIN </th>
      <th> ITEM NAME </th>
      <th> ITEM DESCRIPTION </th>
      <th> LAST UPDATED </th>
    </tr>
  </thead>
  <tbody>
    <% @auin_attributes.each do |row| %>
    <tr>
      <td> <%= row.auin %> </td>
      <td> <%= row.item_name %> </td>
      <td> <%= row.item_desc %> </td>
      <td> <%= row.last_updated %> </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div  class="container-fluid">
  <div class="col-sm-2">
    <h4>MISSING AUIN ATTRIBUTES</h4>
    <h6>Where to find units to catalog attributes.</h6>
    <table class="table table-condensed table-bordered table-striped">
      <thead>
        <tr>
          <th> AUIN </th>
          <th> LOCATION ID </th>
          <th> LOCATION NAME </th>
          <th> QUANTITY </th>
          <th> CONDITION </th>
        </tr>
      </thead>
      <tbody>
        <% @missing_attr.each do |row| %>
        <tr>
          <td> <%= row['auin'] %> </td>
          <td> <%= row['id'] %> </td>
          <td> <%= row['location_name'] %> </td>
          <td> <%= row['quantity'] %> </td>
          <td> <%= row['condition'] %> </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<div>

<h4>IMPORT AUIN ATTRIBUTES</h4>
  <%= form_tag import_edits_auin_index_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "import CSV" %>
  <% end %>
</div>

<div class="btn-group btn-group-toggle" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="radio" name="options" id="add_inv" autocomplete="off" checked> ADD
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="remove_inv" autocomplete="off"> REMOVE
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="replace_inv" autocomplete="off"> REPLACE
  </label>
</div>

inventory/app/views/inventory/edits_inv/index.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>
</div>
<table class="table table-condensed table-bordered table-striped">
  <thead>
    <tr>
      <th> Location ID </th>
      <th> AUIN </th>
      <th> QUANTITY </th>
      <th> CONDITION </th>
    </tr>
  </thead>
  <tbody>
    <% @inv_items.each do |row| %>
    <tr>
      <td> <%= row.location_id %> </td>
      <td> <%= row.auin %> </td>
      <td> <%= row.quantity %> </td>
      <td> <%= row.condition %> </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div>

<h4>IMPORT THAT DATA</h4>
  <%= form_tag import_edits_inv_index_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "import CSV" %>
  <% end %>
</div>

<div class="btn-group btn-group-toggle" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="radio" name="options" id="add_inv" autocomplete="off" checked> ADD
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="remove_inv" autocomplete="off"> REMOVE
  </label>
  <label class="btn btn-primary">
    <input type="radio" name="options" id="replace_inv" autocomplete="off"> REPLACE
  </label>
</div>

inventory/app/views/inventory/views/_inv_views.html.erb
<head>
  <style>
    table { margin-bottom: 12px !import;}
    caption { display: table-caption; text-align: left;}
  </style>
</head>

<div class = "well well-sm">
  <table class="table table-condensed table-bordered table-striped">
    <thead>
      <tr>
        <th> AUIN </th>
        <th> ITEM NAME </th>
        <th> ITEM DESCIPTION </th>
        <th> LAST UPDATED </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= @inv_views_attributes.auin %> </td>
        <td> <%= @inv_views_attributes.item_name %> </td>
        <td> <%= @inv_views_attributes.item_desc %> </td>
        <td> <%= @inv_views_attributes.last_updated %> </td>
      </tr>
    </tbody>
  </table>
</div>

<h4> Inventory Locations </h4>

<div class = "well well-sm">
  <table class="table table-condensed table-bordered table-striped">
    <thead>
      <tr>
        <th> LOCATION_ID </th>
        <th> RECORD QUANTITY </th>
        <th> RECORD CONDITION </th>
        <th> LAST UPDATED </th>
      </tr>
    </thead>
    <tbody>
      <% @inv_views_locations.each do |row| %>
      <tr>
        <td> <%= row['location_id'] %> </td>
        <td> <%= row['quantity'] %> </td>
        <td> <%= row['condition'] %> </td>
        <td> <%= row['last_updated'] %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

inventory/app/views/inventory/views/get_inv_views.js.erb
<% if @inv_views_attributes.blank? %>
$('#sub-doc').html("<h3>No data available corresponding to the inputs giver.</h3>");
<% else %>
$('#sub-doc').html("<%= escape_javascript(render 'inv_views') %>");
<% end %>

inventory/app/views/inventory/views/index.html.erb
<h1>Inventory Status</h1>

<div class="container-fluid">
  <div class="col-sm-2">
    <div class="form-group" style="width: 75%;">
      <label> AUIN </label>
      <input id="auin" class="form-control" type="text" style="width: 70%"> <!-- value="<%= params[:auin] %>"> -->
    </div>
    <div class="btn-group">
      <button type="button" id="lookup_auin" name="button" class="btn btn-success"> Investigate </button>
    </div>
  </div>

  <div class="col-sm-10">
    <div class="well well-sm">
      <div align="center">
        <h4> Inventory Details </h4>
      </div>
    </div>
    <div id="sub-doc"></div>
  </div>
</div>


<script>

$('#lookup_auin').click(function() {
  $('#auin').val($.trim($('#auin').val()));
  if ($('#auin').val().length > 12) {
    $('#sub-doc').html("AUIN has too many characters");
  } else if ($('#auin').val().length = 0) {
    $('#sub-doc').html("AUIN has 0 characters");
  } else {
    $('#sub-doc').html("Loading...")
    $.ajax({
      url: "<%=get_inv_views_path%>",
      type: 'GET',
      dataType: 'script',
      data: {
        auin: $('#auin').val()
      }
    });
  }
});

</script>